# Custom Language File for Launcher Customizer

[ejs.app]
title = "PKH Launcher"

[ejs.landing]
mediaGitHubURL = "https://github.com/PKH-SERVER/PKHLauncher"
mediaTwitterURL = "#"
mediaInstagramURL = "#"
mediaYouTubeURL = "#"
mediaDiscordURL = "https://discord.gg/9Fw7DyA9b8"

[ejs.settings]
sourceGithubLink = "https://github.com/PKH-SERVER/PKHLauncher"
supportLink = "https://github.com/PKH-SERVER/PKHLauncher/issues"

[ejs.welcome]
welcomeHeader = "BIENVENUE SUR PKH !"
welcomeDescription = "Plongez dans un Univers unique avec PKH, une expérience de survie Vanilla+ / Cobblemon inédite qui allie économie, exploration, compétition et collection dans un environnement totalement free-to-play."
welcomeDescCTA = "Plus que quelques clics avant d'arriver sur PKH."
