[ejs.landing]
updateAvailableTooltip = "MISE À JOUR"
usernamePlaceholder = "Nom d'Utilisateur"
usernameEditButton = "Éditer"
settingsTooltip = "Options"
serverStatus = "SERVEUR"
serverStatusPlaceholder = "HORS LIGNE"
mojangStatus = "SERVICES MOJANG"
mojangStatusTooltipTitle = "Status"
mojangStatusNETitle = "Non&nbsp;Essentiel"
newsButton = "NEWS"
launchButton = "JOUER"
launchButtonPlaceholder = "&#8226; Aucun Serveur Sélectionné"
launchDetails = "Chargement.."
newsNavigationStatus = "{currentPage} sur {totalPages}"
newsErrorLoadSpan = "Chargement.."
newsErrorFailedSpan = "Erreur Chargement des News"
newsErrorRetryButton = "Réessayer"
newsErrorNoneSpan = "Aucune News"

[ejs.login]
loginCancelText = "Annuler"
loginSubheader = "CONNEXION MINECRAFT"
loginEmailError = "* Champ Incorrect"
loginEmailPlaceholder = "EMAIL OU NOM D'UTILISATEUR"
loginPasswordError = "* Requis"
loginPasswordPlaceholder = "MOT DE PASSE"
loginForgotPasswordLink = "https://minecraft.net/password/forgot/"
loginForgotPasswordText = "mot de passe oublié?"
loginRememberMeText = "Se souvenir de moi"
loginButtonText = "CONNEXION"
loginNeedAccountLink = "https://minecraft.net/store/minecraft-java-edition/"
loginNeedAccountText = "Créer un compte"
loginPasswordDisclaimer1 = "Votre mot de passe est envoyé directement à mojang et n'est jamais stocké."
loginPasswordDisclaimer2 = "{appName} n'est pas affilié à Mojang AB."

[ejs.loginOptions]
loginOptionsTitle = "Options Connexion"
loginWithMicrosoft = "Connexion Microsoft"
loginWithMojang = "Connexion Mojang"
cancelButton = "Annuler"

[ejs.overlay]
serverSelectHeader = "Serveurs"
serverSelectConfirm = "Choisir"
serverSelectCancel = "Annuler"
accountSelectHeader = "Choisir Compte"
accountSelectConfirm = "Confirmer"
accountSelectCancel = "Annuler"

[ejs.settings]
navHeaderText = "Options"
navAccount = "Compte"
navMinecraft = "Minecraft"
navMods = "Mods"
navJava = "Java"
navLauncher = "Launcher"
navAbout = "À Propos"
navUpdates = "Mises à Jour"
navDone = "Terminé"
tabAccountHeaderText = "Options Compte"
tabAccountHeaderDesc = "Ajouter de nouveaux comptes ou gérer les comptes existants."
microsoftAccount = "Microsoft"
addMicrosoftAccount = "+ Ajouter Compte Microsoft"
mojangAccount = "Mojang"
addMojangAccount = "+ Ajouter Compte Mojang"
minecraftTabHeaderText = "Options Minecraft"
minecraftTabHeaderDesc = "Options de Démarrage"
gameResolutionTitle = "Résolution"
launchFullscreenTitle = "Plein écran"
autoConnectTitle = "Connexion Auto au démarrage"
launchDetachedTitle = "Détacher Launcher du Jeu"
launchDetachedDesc = "Si le Jeu n'est pas détaché, fermer le Launcher fermera le Jeu."
tabModsHeaderText = "Options Mods"
tabModsHeaderDesc = "Activer ou désactiver les mods."
switchServerButton = "Changer"
requiredMods = "Mods Requis"
optionalMods = "Mods Optionnels"
dropinMods = "Mods Intégrés"
addMods = "Ajouter Mods"
dropinRefreshNote = "(F5 - Rafraîchir)"
shaderpacks = "Shaderpacks"
shaderpackDesc = "Activer ou désactiver les shaders. Déconseillé aux Potatoes PC. Vous pouvez ajouter des packs personnalisés ici."
selectShaderpack = "Choisir Shaderpack"
tabJavaHeaderText = "Options Java"
tabJavaHeaderDesc = "Gérer la configuration Java (avancé)."
memoryTitle = "Mémoire"
maxRAM = "RAM Maximum"
minRAM = "RAM Minimum"
memoryDesc = "RAM Minimum recommandée : 10GB / 10048MB. Régler les valeurs minimales et maximales sur la même valeur peut réduire les lags."
memoryTotalTitle = "Total"
memoryAvailableTitle = "Disponible"
javaExecutableTitle = "Java Exe"
javaExecSelDialogTitle = "Choisir Java Executable"
javaExecSelButtonText = "Choisir Fichier"
javaExecDesc = "L'exécutable Java est validé avant le lancement du jeu."
javaPathDesc = "Le chemin doit se terminer par <strong>{pathSuffix}</strong>."
jvmOptsTitle = "Options JVM"
jvmOptsDesc = "Arguments JVM éxécutés au lancement : <em>-Xms</em> and <em>-Xmx</em> ne doit pas être inclus."
launcherTabHeaderText = "Options Launcher"
launcherTabHeaderDesc = "Options relatives au lanceur lui-même."
allowPrereleaseTitle = "Autoriser les màj Beta."
allowPrereleaseDesc = "Les pré-versions comprennent de nouvelles fonctionnalités qui peuvent ne pas avoir été entièrement testées ou intégrées."
dataDirectoryTitle = "Dossier Installation"
selectDataDirectory = "Choisir le Dossier d'installation"
chooseFolder = "Choisir Dossier"
dataDirectoryDesc = "Tous les fichiers de jeu et les installations Java locales seront stockés dans le répertoire data.<br>Les captures d'écran et les sauvegardes du monde sont stockées dans le dossier instance de la configuration serveur correspondante."
aboutTabHeaderText = "À Propos"
aboutTabHeaderDesc = "Notes sur la mise à jour actuelle"
aboutTitle = "{appName}"
stableRelease = "Version Stable"
versionText = "Version "
sourceGithub = "Source (GitHub)"
support = "Aide"
devToolsConsole = "DevTools Console"
releaseNotes = "Note MàJ"
changelog = "Changelog"
noReleaseNotes = "Aucune Note"
viewReleaseNotes = "Voir les notes de version sur GitHub"
launcherUpdatesHeaderText = "MàJ Launcher"
launcherUpdatesHeaderDesc = "Télécharger, installer et vérifier les mises à jour du lanceur."
checkForUpdates = "Vérifier Mise à Jour"
whatsNew = "Infos & News"
updateReleaseNotes = "Notes de mise à jour"

[ejs.waiting]
waitingText = "En Attente de Microsoft.."

[ejs.welcome]
continueButton = "CONTINUER"


[js.discord]
waiting = "En Attente du Client.."
state = "Serveur: {shortId}"

[js.index]
microsoftLoginTitle = "Connexion Microsoft"
microsoftLogoutTitle = "Déconnexion Microsoft"

[js.login]
login = "CONNEXION"
loggingIn = "CONNECTÉ"
success = "RÉUSSITE"
tryAgain = "Réessayer"

[js.login.error]
invalidValue = "* Champ Incorrect"
requiredValue = "* Requis"

[js.login.error.unknown]
title = "Erreur Inconnue à la Connexion"
desc = "Une erreur inconnue s'est produite. Veuillez consulter la console pour plus de détails."

[js.landing.launch]
pleaseWait = "Chargement.."
failureTitle = "Erreur de Démarrage"
failureText = "Voir Console (CTRL + Shift + i) pour plus d'infos."
okay = "OK"

[js.landing.selectedAccount]
noAccountSelected = "Aucun Compte sélectionné"

[js.landing.selectedServer]
noSelection = "Aucun Serveur sélectionné"
loading = "Chargement.."

[js.landing.serverStatus]
server = "SERVEUR"
offline = "HORS LIGNE"
players = "JOUEURS"

[js.landing.systemScan]
checking = "Analyse info système.."
noCompatibleJava = "Aucune installation Java<br>compatible n'a été trouvée"
installJavaMessage = "Pour lancer Minecraft, vous devez disposer d'une installation 64 bits de Java {major}. Voulez-vous que nous en installions une copie ?"
installJava = "Installer Java"
installJavaManually = "Installer Manuellement"
javaDownloadPrepare = "Préparation de Java.."
javaDownloadFailureTitle = "Erreur durant le téléchargement de Java"
javaDownloadFailureText = "Voir console (CTRL + Shift + i) pour plus d'infos."
javaRequired = "Java Requis<br>pour Lancer"
javaRequiredMessage = 'A valid x64 installation of Java {major} is required to launch.<br><br>Please refer to our <a href="https://github.com/dscalzi/HeliosLauncher/wiki/Java-Management#manually-installing-a-valid-version-of-java">Java Management Guide</a> for instructions on how to manually install Java.'
javaRequiredDismiss = "Compris"
javaRequiredCancel = "Retour"

[js.landing.downloadJava]
findJdkFailure = "OpenJDK distribution introuvable."
javaDownloadCorruptedError = "Hash invalide sur le JDK téléchargé, le fichier peut être corrompu."
extractingJava = "Extraction Java"
javaInstalled = "Java Installé!"

[js.landing.dlAsync]
loadingServerInfo = "Chargement info serveur.."
fatalError = "Erreur Fatale"
unableToLoadDistributionIndex = "Impossible de charger une copie de l'index. Voir Console (CTRL + Shift + i) pour plus d'infos."
pleaseWait = "Chargement.."
errorDuringLaunchTitle = "Error During Launch"
seeConsoleForDetails = "See console (CTRL + Shift + i) for more details."
validatingFileIntegrity = "Validating file integrity.."
errorDuringFileVerificationTitle = "Error During File Verification"
downloadingFiles = "Téléchargement.."
errorDuringFileDownloadTitle = "Erreur durant le Téléchargement"
preparingToLaunch = "Lancement en cours.."
launchingGame = "Lancement.."
launchWrapperNotDownloaded = "LaunchWrapper n'a pas été téléchargé correctement. Le jeu ne peut pas se lancer.<br><br>Pour résoudre ce problème, désactivez temporairement votre logiciel antivirus et relancez le jeu.<br><br>N'oubliez pas de faire un report sur le Discord ou depuis le Launcher."
doneEnjoyServer = "Terminé. Bienvenue sur PKH!"
checkConsoleForDetails = "Voir Console (CTRL + Shift + i) pour plus d'infos."

[js.landing.news]
checking = "Chargement des News"

[js.landing.discord]
loading = "Chargement.."
joining = "En route pour PKH"
joined = "Une expérience Vanilla+ & Cobblemon Inédite!"

[js.overlay]
dismiss = "Décliner"

[js.settings.fileSelectors]
executables = "Executables"
allFiles = "All Files"

[js.settings.mstfLogin]
errorTitle = "Une Erreur est survenue"
errorMessage = "Erreur Connexion Microsoft. Veuillez Réessayer."
okButton = "OK"

[js.settings.mstfLogout]
errorTitle = "Une Erreur est survenue"
errorMessage = "Erreur Déconnexion Microsoft. Veuillez Réessayer."
okButton = "OK"

[js.settings.authAccountSelect]
selectButton = "Choisir Compte"
selectedButton = "Compte Choisi &#10004;"

[js.settings.authAccountLogout]
lastAccountWarningTitle = "Attention<br>Dernier Compte"
lastAccountWarningMessage = "Pour utiliser le Launcher, au moins un compte doit être connecté. Vous devrez vous connecter après.<br><br>Êtes-vous sûr de vouloir vous déconnecter?"
confirmButton = "Confirmer"
cancelButton = "Annuler"

[js.settings.authAccountPopulate]
username = "Compte"
uuid = "UUID"
selectAccount = "Choisir Compte"
selectedAccount = "Compte Choisi ✓"
logout = "Déconnecter"

[js.settings.dropinMods]
removeButton = "Supprimer"
deleteFailedTitle = "Erreur Suppression<br>Mod Intégré {fullName}"
deleteFailedMessage = "Assurez-vous que le fichier n'est pas utilisé et réessayez."
failedToggleTitle = "Erreur Activation<br>Un ou Plus Mods Intégrés"
okButton = "OK"

[js.settings.serverListing]
mainServer = "Serveur Principal"

[js.settings.java]
selectedJava = "Actuel: Java {version} ({vendor})"
invalidSelection = "Sélection Invalide"
requiresJava = "Requiert Java {major} x64."
availableOptions = "Options disponibles pour Java {major} (HotSpot VM)"

[js.settings.about]
preReleaseTitle = "Bêta"
stableReleaseTitle = "Version stable"
releaseNotesFailed = "Échec du chargement des notes"

[js.settings.updates]
newReleaseTitle = "Nouvelle Bersion"
newPreReleaseTitle = "Nouvelle Beta"
downloadingButton = "Téléchargement.."
downloadButton = 'Depuis Github<span style="font-size: 10px;color: gray;text-shadow: none !important;">Fermer launcher et exécuter dmg.</span>'
latestVersionTitle = "Vous jouez sur la dernière version"
checkForUpdatesButton = "Vérifier MàJ"
checkingForUpdatesButton = "Vérification des MàJ"

[js.settings.msftLogin]
errorTitle = "Connection à Microsoft échoué"
errorMessage = "Compte Micosoft introuvable ou invalide.Essayez à nouveau."
okButton = "OK"

[js.uibinder.startup]
fatalErrorTitle = "Erreur fatale: Impossible de charger l’index"
fatalErrorMessage = "Impossible d’établir une connexion avec nos serveurs pour télécharger l’index. Aucune copie locale n’était disponible.<br><br>L’index est un fichier essentiel qui fournit les dernières informations du serveur. Le lanceur ne peut pas démarrer sans lui. Assurez-vous d’être connecté à Internet et relancez l’application."
closeButton = "Fermer"

[js.uibinder.validateAccount]
failedMessageTitle = "Échec de l'actualisation"
failedMessage = "Connexion de <strong>{account}</strong> impossible. Choisissez un autre compte."
failedMessageSelectAnotherAccount = "Connexion de <strong>{account}</strong> impossible. Reconnectez-vous."
loginButton = "Connexion"
selectAnotherAccountButton = "Choisir compte"

[js.uicore.autoUpdate]
checkingForUpdateButton = "Vérification des MàJ"
installNowButton = "Installer"
checkForUpdatesButton = "Vérifier MàJ"

[js.auth.microsoft.error]
noProfileTitle = "Erreur de Connexion:<br> Profil Introuvable"
noProfileDesc = "Si vous n'avez pas encore acheté le jeu, vous pouvez le faire sur <a href=« https://minecraft.net// »>Minecraft.net</a>.<br><br>.Si vous avez récemment acheté le jeu ou que vous l'avez obtenu grâce au Xbox Game Pass, vous devez configurer votre profil sur le site Officiel <a href=\«  https://minecraft.net/\ »>Minecraft.net</a>."
noXboxAccountTitle = "Erreur de Connexion:<br>Aucun Compte Xbox"
noXboxAccountDesc = "Votre compte Microsoft n'est pas associé à un compte Xbox."
xblBannedTitle = "Erreur de Connexion:<br>Xbox Direct Indisponible"
xblBannedDesc = "Votre compte Microsoft vient d'un pays où Xbox est banni ou est indisponible."
under18Title = "Erreur de Connexion:<br>Accord parental requis."
under18Desc = "Les comptes -18 doivent appartenir à une Famille sous accord parental."
unknownTitle = "Erreur de Connexion Inconnue"
unknownDesc = "Erreur de Connexion Inconnue. Voir Console pour plus d'infos'"

[js.auth.mojang.error]
methodNotAllowedTitle = "Erreur Interne:<br>Méthode interdite"
methodNotAllowedDesc = "Méthode interdite. Signaler cette erreur s'il-vous-plaît."
notFoundTitle = "Erreur Interne:<br>Introuvable"
notFoundDesc = "Le point final d'authentification n'a pas été trouvé. Signaler cette erreur s'il-vous-plaît."
accountMigratedTitle = "Erreur de Connexion:<br>Compte Migré"
accountMigratedDesc = "Vous avez essayé de vous connecter avec un compte migré. Réessayez en utilisant l'email du compte comme nom du compte."
invalidCredentialsTitle = "Erreur de Connexion:<br>Identifiants invalides"
invalidCredentialsDesc = "L'email ou le MdP que vous avez entré est incorrect. Réessayez encore."
tooManyAttemptsTitle = "Erreur de Connexion:<br>Trop d'essais"
tooManyAttemptsDesc = "Il y a eu trop de tentatives de connexion. Réssayez plus tard."
invalidTokenTitle = "Erreur de Connexion:<br>Token Invalide"
invalidTokenDesc = "Le token d'accès fourni est invalide."
tokenHasProfileTitle = "Erreur de Connexion:<br>Token déjà attribué au profil"
tokenHasProfileDesc = "Un profil a déjà été attribué au token. La sélection des profils n'est pas encore implémentée."
credentialsMissingTitle = "Erreur de Connexion:<br>Champs requis Manquants"
credentialsMissingDesc = "Nom de Compte/Mot de passe invalide ou le mot de passe comporte moins de 3 caractères."
invalidSaltVersionTitle = "Erreur de Connexion:<br>Version salt invalide"
invalidSaltVersionDesc = "Version salt invalide."
unsupportedMediaTypeTitle = "Erreur Interne:<br>Fichier média invalide"
unsupportedMediaTypeDesc = "Type de fichier non pris en charge. Veuillez signaler cette erreur."
accountGoneTitle = "Erreur de Connexion:<br>Compte Migré"
accountGoneDesc = "Le compte a été migré vers un compte Microsoft. Veuillez vous connecter avec Microsoft."
unreachableTitle = "Erreur de Connexion:<br>Inaccessible"
unreachableDesc = "Impossible de joindre les serveurs de connexion. Vérifiez qu'ils sont en ligne et votre connexion réseau."
gameNotPurchasedTitle = "Erreur de Connexion:<br>Jeu non possédé"
gameNotPurchasedDesc = "Le compte avec lequel vous essayez de vous connecter n'a pas acheté de copie de Minecraft. Vous pouvez acheter une copie sur <a href=\"https://minecraft.net/\">Minecraft.net</a>"
unknownErrorTitle = "Erreur Inconnue de Connexion"
unknownErrorDesc = "Erreur Inconnue survenue. Voir Console pour plus d'infos."
